name = "farmstand"
compatibility_date = "2024-11-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "farmstand"
database_id = "05be80b4-3654-4ac6-a81b-aee87b0158a4"  # wrangler d1 create farmstand

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "farmstand-assets"

[vars]
ENVIRONMENT = "production"
R2_PUBLIC_URL = "https://img.farmstand.paleotreats.com"
ALLOWED_ORIGIN = "https://farmstand.paleotreats.com"

[dev]
port = 8788
local_protocol = "http"
